- type: gameMapPool
  id: DefaultStarlightMapPool
  maps:
  - StarlightBagel
  - StarlightCog
#  - StarlightCork # SpL
  - StarlightFland
  - StarlightHotel
  - StarlightLagan
  - StarlightLeth
  - StarlightLobster
  - StarlightManor
  - StarlightMing
  - StarlightOasis
  - StarlightOrwell
  - StarlightReach
  - StarlightSaltern
  - StarlightSepultum
  - StarlightStarboard
  - StarlightKiloton
  - StarlightElkridge
#  - StarlightPrism # SpL
  - StarlightSilica
  - StarlightCluster
  - StarlightBox
  - StarlightPlasma
  - StarlightPacked
  - StarlightSpaceMall
  - StarlightBoxcars
  - StarlightSerpentcrest
#  - StarlightBarratry # SpL
# SpL Start
  - SpLBazaar
  - SpLPrefab
  - SpLFrontier
  - SpLOmega
  - SpLBarratry
  - SpLPrism
  - SpLCork
# SpL End
