- type: entity
  name: non-lethal weapons safe
  id: GunSafeNonLethals
  parent: [GunSafeBaseArmorySL, BaseSecurityContraband]
  components:
    - type: EntityStorageVisuals
      stateDoorClosed: nonlethal_gunsafe_doors
    - type: EntityTableContainerFill
      containers:
        entity_storage: !type:AllSelector
          children:
            - id: WeaponShotgunRiotRubber
              amount: 2
            - id: WeaponSubMachineGunSP91RCRubber
              amount: 2
            - id: MagazinePistolSubMachineGunRubber
              amount: 2
            - id: MagazineBoxPistolRubber
              amount: 2
            - id: BoxBeanbag
              amount: 2
            - id: SpeedLoaderShotgunBeanbag
              amount: 2
            - id: WeaponLauncherPeacekeeper
              amount: 2
            - id: BoxPeacekeeperGas
              amount: 2
            - id: BoxPeacekeeperStinger
              amount: 2
            - id: BoxPeacekeeperFlash
              amount: 2
            - id: BoxPeacekeeperBaton
              amount: 2