# Sidearm Options
- type: loadout
  id: HOSSP8AR
  dummyEntity: WeaponPistolSP8AR
  storage:
    back:
      - WeaponPistolSP8AR
      - MagazinePistol40SP

- type: loadout
  id: HOSDeckard
  dummyEntity: WeaponRevolverDeckard
  storage:
    back:
      - WeaponRevolverDeckard
      - SpeedLoaderMagnumSP
      - SpeedLoaderMagnumSP

- type: loadout
  id: HOSPistolDeagle
  dummyEntity: WeaponPistolDeagleNT
  storage:
    back:
      - WeaponPistolDeagleNT
      - MagazineMagnum