- type: antag
  id: LoneAbductorAntag
  name: abductors-ghost-role-name
  antagonist: true
  objective: roles-antag-abductor-objective
  requirements:
  - !type:RoleTimeRequirement
    role: JobSecurityOfficer
    time: 1h # SpL
  - !type:RoleTimeRequirement
    role: JobSurgeon
    time: 1h # SpL
  - !type:OverallPlaytimeRequirement # SpL
    time: 10h # SpL
  playTimeTracker: AntagLoneAbductor
