- type: listing
  id: VendorMiningWeaponMiningLaser
  productEntity: WeaponMiningLaser
  cost:
    SalvageTicket: 500
  categories:
    - MiningEquipment
  conditions:
    - !type:ListingLimitedStockCondition
      stock: 3
    - !type:BuyerAccessCondition
  
- type: listing
  id: VendorMiningWeaponHoloflarePistol
  productEntity: WeaponHoloflarePistol
  cost:
    SalvageTicket: 500
  categories:
    - MiningEquipment
  conditions:
    - !type:BuyerAccessCondition   
  
