- type: listing
  id: VendorSalvageWeaponRifleM18
  productEntity: WeaponRifleM18
  cost:
    SalvageTicket: 500
  categories:
    - SalvageWeapons
  conditions:
    - !type:BuyerAccessCondition

- type: listing
  id: VendorSalvageWeaponHoloflarePistol
  productEntity: WeaponHoloflarePistol
  cost:
    SalvageTicket: 500
  categories:
    - SalvageEquipment
  conditions:
    - !type:BuyerAccessCondition   