- type: job
  id: Magistrate
  name: job-name-magistrate
  description: job-description-magistrate
  playTimeTracker: JobMagistrate
  requirements:
    - !type:DepartmentTimeRequirement
      department: Command
      time: 5h # SpL start
#    - !type:DepartmentTimeRequirement
#      department: Security
#      time: 5h 
    - !type:RoleTimeRequirement 
      role: JobIAA 
      time: 1h 
    - !type:OverallPlaytimeRequirement 
      time: 20h 
#    - !type:RolesRequirement # SpL- nah
#      proto: ExtRolesReq # Spl end
  startingGear: MagistrateGear
  icon: "JobIconMagistrate"
  rules: job-rules-corporate-aligned
  supervisors: job-supervisors-nanotrasen
  canBeAntag: false
  setPreference: true
  displayWeight: 4
  access:
  - Magistrate
  - IAA
  - Lawyer
  - Brig
  - Security
  - Command
  - Maintenance
  - GenpopEnter
  - GenpopLeave
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff

- type: startingGear
  id: MagistrateGear
  equipment:
    #jumpsuit: MagistrateUniformSuit
    #shoes: ClothingShoesBootsLaceup
    #eyes: ClothingEyesGlassesSecurity
    #gloves: ClothingHandsGlovesColorWhite
    #outerClothing: ClothingOuterRobesJudge
    id: MagistratePDA
    ears: ClothingHeadsetMagistrate
    #head: ClothingHeadHatPwig
    belt: BoxFolderNanoTrasenClipboard
  storage:
    back:
    - RubberStampMagistrate
    - ClothingNeckLawyerbadge
    - GavelHammer
    - GavelBlock
    - Flash
    #- MagistrateUniformSkirt

- type: chameleonOutfit
  id: MagistrateChameleonOutfit
  job: Magistrate
  equipment:
    head: ClothingHeadHatPwig
    eyes: ClothingEyesGlassesSecurity
    outerClothing: ClothingOuterRobesJudge
    misc: ClothingNeckLawyerbadge # Starlight change slot to misc.
    gloves: ClothingHandsGlovesColorWhite
