- type: job
  id: NanotrasenCareerTrainer
  name: job-name-nct
  description: job-description-nct
  playTimeTracker: JobNanotrasenCareerTrainer
  requirements: # SpL start
#    - !type:RolesRequirement # SpL- this is why we ever have NCTs
#      proto: StaffAndMentorOnlyRolesReq
    - !type:DepartmentTimeRequirement
      department: Cargo
      time: 1h
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 1h
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 1h
    - !type:DepartmentTimeRequirement
      department: Science
      time: 1h
    - !type:DepartmentTimeRequirement
      department: Civilian
      time: 1h
    - !type:OverallPlaytimeRequirement
      time: 20h # You gotta know what you're doing to teach it
    - !type:TraitsRequirement
      traits:
#        - Iterator # SpL end
        - Muted
      inverted: true
  startingGear: NanotrasenCareerTrainerGear
  icon: JobIconNanotrasenCareerTrainer
  rules: job-rules-corporate-aligned
  supervisors: job-supervisors-nt-personnel
  displayWeight: 2
  overrideConsoleVisibility: false
  canBeAntag: false
  joinNotifyCrew: true
  access:
    - Lawyer
    - Command
    - Service
    - Maintenance
    - Theatre
    - External
    - Engineering
    - Research
    - Security
    - Cargo
    - Mail
    - Medical
    - IAA
  special:
    - !type:AddImplantSpecial
      implants: [MindShieldImplant]
    - !type:AddComponentSpecial
      components:
        - type: NoObjectiveTarget
        - type: NCTAgent

- type: startingGear
  id: NanotrasenCareerTrainerGear
  equipment:
    id: NanoTrasenCareerTrainerPDA
    ears: ClothingHeadsetNCT
    neck: Whistle
    pocket1: nctdatachip
    pocket2: PinpointerUniversal
    belt: BoxFolderNanoTrasenClipboard
    gloves: ClothingHandsGlovesColorWhite
    outerClothing: ClothingOuterCoatNCT
  storage:
    back:
      - Flash

- type: chameleonOutfit
  id: NanotrasenCareerTrainerChameleonOutfit
  job: NanotrasenCareerTrainer
  hasMindShield: true
  equipment:
    outerClothing: ClothingOuterCoatNCT
